name: sundlf-replace
services:
  laravel:
    build: ./infra/dev/laravel
    container_name: sundlf-laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./infra/laravel/php.ini:/usr/local/etc/php/php.ini
    tty: true
    stdin_open: true
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:12
    container_name: sundlf-mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./infra/dev/mariadb/.env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./infra/dev/mariadb/init:/docker-entrypoint-initdb.d
      - ./infra/dev/mariadb/my.conf:/etc/mysql/conf.d/my.cnf

volumes:
  mariadb_data:
